# Generated by Django 3.0.8 on 2020-07-10 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ref', models.CharField(db_index=True, max_length=255)),
                ('opted_in', models.BooleanField(default=True)),
                ('entity', models.CharField(blank=True, choices=[('asset', 'Asset'), ('account', 'Account'), ('customer', 'Customer'), ('user', 'User'), ('marketing', 'Marketing')], max_length=50)),
                ('entity_id', models.CharField(blank=True, max_length=255)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='preferences.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(choices=[('email', 'eMail'), ('sms', 'SMS'), ('push', 'Push Notification'), ('inapp', 'In-App')], max_length=100)),
                ('medium_value', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('preferences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediums', to='preferences.Preference')),
            ],
        ),
    ]
