# Generated by Django 3.0.8 on 2020-07-13 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medium',
            old_name='preferences',
            new_name='preference',
        ),
    ]
